# Visual SlickEdit generated file.  Do not edit this file except in designated areas.
# -----Begin user-editable area-----

# -----End user-editable area-----

# Make command to use for dependencies
MAKECMD=gmake

# If no configuration is specified, "Debug" will be used
ifndef "CFG"
CFG=Debug
endif

#
# Configuration: Release
#
ifeq "$(CFG)" "Release"
OUTDIR=Release
OUTFILE=httpd
CFG_INC=
CFG_LIB=
CFG_OBJ=
COMMON_OBJ=$(OUTDIR)/DDescript.o $(OUTDIR)/DException.o \
	$(OUTDIR)/DFile.o $(OUTDIR)/DFork.o $(OUTDIR)/DHttpRequest.o \
	$(OUTDIR)/DList.o $(OUTDIR)/DMain.o $(OUTDIR)/DObject.o \
	$(OUTDIR)/DSemaphore.o $(OUTDIR)/DServerd.o $(OUTDIR)/DSharedMem.o \
	$(OUTDIR)/DSignal.o $(OUTDIR)/DSocket.o $(OUTDIR)/DString.o 
OBJ=$(COMMON_OBJ) $(CFG_OBJ)

COMPILE=g++ -c  -ansi -Wall -pedantic -o "$(OUTDIR)/$(*F).o" $(CFG_INC) "$<"
LINK=g++  -Wall -pedantic -o "$(OUTDIR)/httpd" $(OBJ) $(CFG_LIB)

# Pattern rules
$(OUTDIR)/%.o : source/%.c
	$(COMPILE)

$(OUTDIR)/%.o : source/%.cpp
	$(COMPILE)

# Build rules
all: $(OUTDIR)/$(OUTFILE)

$(OUTDIR)/$(OUTFILE): $(OUTDIR)  $(OBJ)
	$(LINK)

$(OUTDIR):
	mkdir -p "$(OUTDIR)"
endif

#
# Configuration: Debug
#
ifeq "$(CFG)" "Debug"
OUTDIR=Debug
OUTFILE=httpd
CFG_INC=
CFG_LIB=
CFG_OBJ=
COMMON_OBJ=$(OUTDIR)/DDescript.o $(OUTDIR)/DException.o \
	$(OUTDIR)/DFile.o $(OUTDIR)/DFork.o $(OUTDIR)/DHttpRequest.o \
	$(OUTDIR)/DList.o $(OUTDIR)/DMain.o $(OUTDIR)/DObject.o \
	$(OUTDIR)/DSemaphore.o $(OUTDIR)/DServerd.o $(OUTDIR)/DSharedMem.o \
	$(OUTDIR)/DSignal.o $(OUTDIR)/DSocket.o $(OUTDIR)/DString.o 
OBJ=$(COMMON_OBJ) $(CFG_OBJ)

COMPILE=g++ -c  -ansi -g -Wall -pedantic -o "$(OUTDIR)/$(*F).o" $(CFG_INC) "$<"
LINK=g++  -g -Wall -pedantic -o "$(OUTDIR)/httpd" $(OBJ) $(CFG_LIB)

# Pattern rules
$(OUTDIR)/%.o : source/%.c
	$(COMPILE)

$(OUTDIR)/%.o : source/%.cpp
	$(COMPILE)

# Build rules
all: $(OUTDIR)/$(OUTFILE)

$(OUTDIR)/$(OUTFILE): $(OUTDIR)  $(OBJ)
	$(LINK)

$(OUTDIR):
	mkdir -p "$(OUTDIR)"
endif

# Clean this project
clean:
	rm -f $(OUTDIR)/$(OUTFILE)
	rm -f $(OBJ)

# Clean this project and all dependencies
cleanall: clean
